version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-docker
    restart: always
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TZ: Asia/Seoul
    depends_on:
      - mysql
      - redis
    networks:
      - loan-network

  nginx:
    image: nginx:latest
    container_name: nginx-docker
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - loan-network

  mysql:
    image: mysql:latest
    container_name: mysql-docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: loan
      TZ: Asia/Seoul
    networks:
      - loan-network

  redis:
    image: redis:latest
    container_name: redis-docker
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge