version: "3.8"

services:
  module-core:
    image: kingseungil/module-core:1.0.0
    container_name: module-core
    env_file:
      - env.properties
    networks:
      - loan-network

  module-user:
    image: kingseungil/module-user:1.0.0
    container_name: module-user
    expose:
      - "8080"
    depends_on:
      - module-core
      - mysql
      - redis
    networks:
      - loan-network

  module-organization:
    image: kingseungil/module-organization:1.0.0
    container_name: module-organization
    expose:
      - "8080"
    depends_on:
      - module-core
      - mysql
      - redis
    networks:
      - loan-network

  nginx:
    image: nginx:latest
    container_name: nginx-docker
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - module-user
      - module-organization
      - module-core
      - mysql
      - redis
    networks:
      loan-network:

  mysql:
    image: mysql:latest
    container_name: mysql-docker
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-data:/var/lib/mysql
    env_file:
      - env.properties
    environment:
      TZ: Asia/Seoul
    networks:
      - loan-network

  redis:
    image: redis:latest
    container_name: redis-docker
    ports:
      - "6379:6379"
    volumes:
      - ../redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - loan-network

networks:
  loan-network:
    driver: bridge